

//<h2>Primitive Data Types</h2>
    

    //Using Strings
    var name="haritha";
    var education='B.tech';
    var gender= `female`;
    console.log(name);
    console.log(typeof education);

    //Using number
    var age=25;
    var salary=85000.00;
    console.log(age);
    console.log(typeof age);

    //using undefinied
    var name1;
    console.log(name1);
    console.log(typeof name1);

    //using null
    var data=null;
    console.log(data);
    console.log(typeof data);

    //Uncaught ReferenceError: qualification is not defined
   // console.log(qualification);
   var name3="xyz";

